/* This file is generated by scripts/generate-realtime-contracts.mjs. Do not edit. */
import type { FromSchema } from 'json-schema-to-ts'

export const handshakeV1Schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://mentalbridge.dev/contracts/websocket/realtime/handshake-v1.schema.json',
  title: 'Realtime authenticated handshake v1',
  type: 'object',
  additionalProperties: false,
  required: ['schemaVersion', 'accessToken'],
  properties: {
    schemaVersion: {
      const: 1,
    },
    accessToken: {
      type: 'string',
      minLength: 1,
      maxLength: 8192,
    },
    correlationId: {
      type: 'string',
      minLength: 1,
      maxLength: 128,
      pattern: '^[A-Za-z0-9._:-]+$',
    },
  },
} as const

export const commandEnvelopeV1Schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://mentalbridge.dev/contracts/websocket/realtime/command-envelope-v1.schema.json',
  title: 'Realtime client command envelope v1',
  oneOf: [
    {
      $ref: '#/$defs/heartbeat',
    },
    {
      $ref: '#/$defs/subscribe',
    },
    {
      $ref: '#/$defs/sendMessage',
    },
  ],
  $defs: {
    base: {
      type: 'object',
      required: [
        'schemaVersion',
        'commandId',
        'commandType',
        'correlationId',
        'sentAt',
        'payload',
      ],
      properties: {
        schemaVersion: {
          const: 1,
        },
        commandId: {
          type: 'string',
          format: 'uuid',
        },
        commandType: {
          type: 'string',
          enum: [
            'presence.heartbeat',
            'conversation.subscribe',
            'message.send',
          ],
        },
        correlationId: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
          pattern: '^[A-Za-z0-9._:-]+$',
        },
        sentAt: {
          type: 'string',
          format: 'date-time',
        },
        payload: {
          type: 'object',
        },
      },
    },
    heartbeat: {
      allOf: [
        {
          $ref: '#/$defs/base',
        },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            schemaVersion: true,
            commandId: true,
            commandType: {
              const: 'presence.heartbeat',
            },
            correlationId: true,
            sentAt: true,
            payload: {
              type: 'object',
              additionalProperties: false,
            },
          },
        },
      ],
    },
    subscribe: {
      allOf: [
        {
          $ref: '#/$defs/base',
        },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            schemaVersion: true,
            commandId: true,
            commandType: {
              const: 'conversation.subscribe',
            },
            correlationId: true,
            sentAt: true,
            payload: {
              type: 'object',
              additionalProperties: false,
              required: ['conversationId'],
              properties: {
                conversationId: {
                  type: 'string',
                  format: 'uuid',
                },
              },
            },
          },
        },
      ],
    },
    sendMessage: {
      allOf: [
        {
          $ref: '#/$defs/base',
        },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            schemaVersion: true,
            commandId: true,
            commandType: {
              const: 'message.send',
            },
            correlationId: true,
            sentAt: true,
            payload: {
              type: 'object',
              additionalProperties: false,
              required: [
                'conversationId',
                'clientMessageId',
                'type',
                'content',
              ],
              properties: {
                conversationId: {
                  type: 'string',
                  format: 'uuid',
                },
                clientMessageId: {
                  type: 'string',
                  format: 'uuid',
                },
                type: {
                  const: 'TEXT',
                },
                content: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 4000,
                },
              },
            },
          },
        },
      ],
    },
  },
} as const

export const acknowledgementV1Schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://mentalbridge.dev/contracts/websocket/realtime/acknowledgement-v1.schema.json',
  title: 'Realtime acknowledgement v1',
  type: 'object',
  additionalProperties: false,
  required: [
    'schemaVersion',
    'commandId',
    'correlationId',
    'status',
    'acknowledgedAt',
  ],
  properties: {
    schemaVersion: {
      const: 1,
    },
    commandId: {
      type: 'string',
      format: 'uuid',
    },
    correlationId: {
      type: 'string',
      minLength: 1,
      maxLength: 128,
    },
    status: {
      type: 'string',
      enum: ['accepted', 'duplicate'],
    },
    acknowledgedAt: {
      type: 'string',
      format: 'date-time',
    },
    messageId: {
      type: 'string',
      format: 'uuid',
    },
    liveDelivery: {
      type: 'string',
      enum: ['delivered', 'degraded', 'not_applicable'],
      description:
        'not_applicable until cross-instance fan-out or receipt evidence can prove live delivery',
    },
  },
} as const

export const errorV1Schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://mentalbridge.dev/contracts/websocket/realtime/error-v1.schema.json',
  title: 'Realtime safe error v1',
  type: 'object',
  additionalProperties: false,
  required: ['schemaVersion', 'correlationId', 'code', 'message', 'retryable'],
  properties: {
    schemaVersion: {
      const: 1,
    },
    commandId: {
      type: 'string',
      format: 'uuid',
    },
    correlationId: {
      type: 'string',
      minLength: 1,
      maxLength: 128,
    },
    code: {
      type: 'string',
      enum: [
        'AUTHENTICATION_REQUIRED',
        'AUTHENTICATION_EXPIRED',
        'INVALID_ENVELOPE',
        'UNSUPPORTED_SCHEMA_VERSION',
        'PAYLOAD_TOO_LARGE',
        'RATE_LIMITED',
        'ACCESS_DENIED',
        'CHAT_ELIGIBILITY_UNAVAILABLE',
        'IDEMPOTENCY_CONFLICT',
        'DEPENDENCY_UNAVAILABLE',
        'INTERNAL_ERROR',
      ],
    },
    message: {
      type: 'string',
      minLength: 1,
      maxLength: 200,
    },
    retryable: {
      type: 'boolean',
    },
  },
} as const

export const serverEventV1Schema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://mentalbridge.dev/contracts/websocket/realtime/server-event-v1.schema.json',
  title: 'Realtime server event v1',
  oneOf: [
    {
      $ref: '#/$defs/connectionReady',
    },
    {
      $ref: '#/$defs/messageCreated',
    },
  ],
  $defs: {
    base: {
      type: 'object',
      required: [
        'schemaVersion',
        'eventId',
        'eventType',
        'correlationId',
        'occurredAt',
        'payload',
      ],
      properties: {
        schemaVersion: {
          const: 1,
        },
        eventId: {
          type: 'string',
          format: 'uuid',
        },
        eventType: {
          type: 'string',
          enum: ['connection.ready', 'message.created'],
        },
        correlationId: {
          type: 'string',
          minLength: 1,
          maxLength: 128,
        },
        occurredAt: {
          type: 'string',
          format: 'date-time',
        },
        payload: {
          type: 'object',
        },
      },
    },
    connectionReady: {
      allOf: [
        {
          $ref: '#/$defs/base',
        },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            schemaVersion: true,
            eventId: true,
            eventType: {
              const: 'connection.ready',
            },
            correlationId: true,
            occurredAt: true,
            payload: {
              type: 'object',
              additionalProperties: false,
              required: ['accountId', 'role', 'presence'],
              properties: {
                accountId: {
                  type: 'string',
                  format: 'uuid',
                },
                role: {
                  type: 'string',
                  enum: ['USER', 'SPECIALIST', 'ADMIN'],
                },
                presence: {
                  type: 'string',
                  enum: ['connected', 'degraded'],
                },
              },
            },
          },
        },
      ],
    },
    messageCreated: {
      allOf: [
        {
          $ref: '#/$defs/base',
        },
        {
          type: 'object',
          additionalProperties: false,
          properties: {
            schemaVersion: true,
            eventId: true,
            eventType: {
              const: 'message.created',
            },
            correlationId: true,
            occurredAt: true,
            payload: {
              type: 'object',
              additionalProperties: false,
              required: [
                'messageId',
                'conversationId',
                'senderId',
                'clientMessageId',
                'type',
                'content',
                'sentAt',
                'schemaVersion',
              ],
              properties: {
                messageId: {
                  type: 'string',
                  format: 'uuid',
                },
                conversationId: {
                  type: 'string',
                  format: 'uuid',
                },
                senderId: {
                  type: 'string',
                  format: 'uuid',
                },
                clientMessageId: {
                  type: 'string',
                  format: 'uuid',
                },
                type: {
                  const: 'TEXT',
                },
                content: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 4000,
                },
                sentAt: {
                  type: 'string',
                  format: 'date-time',
                },
                schemaVersion: {
                  const: 1,
                },
              },
            },
          },
        },
      ],
    },
  },
} as const

export type HandshakeV1 = FromSchema<typeof handshakeV1Schema>
export type CommandEnvelopeV1 = FromSchema<typeof commandEnvelopeV1Schema>
export type AcknowledgementV1 = FromSchema<typeof acknowledgementV1Schema>
export type SafeErrorV1 = FromSchema<typeof errorV1Schema>
export type ServerEventV1 = FromSchema<typeof serverEventV1Schema>
