/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/support-guides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSupportGuides"];
        put?: never;
        post: operations["generateSupportGuide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/support-guides/{supportGuideId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSupportGuide"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateSupportGuideRequest: {
            /** Format: uuid */
            phq9AssessmentId: string;
            /** Format: uuid */
            gad7AssessmentId: string;
        };
        SupportGuide: {
            /** Format: uuid */
            supportGuideId: string;
            /** @constant */
            guideVersion: 1;
            /** @constant */
            guidePolicyVersion: "mb-support-guide-capstone-v1";
            /** Format: uuid */
            supportEvaluationId: string;
            /** Format: date-time */
            generatedAt: string;
            /** @constant */
            guideType: "ONE_TIME_SUPPORT_GUIDE";
            explanation: {
                code: string;
                text: string;
            };
            safety: {
                /** @enum {string} */
                status: "NEGATIVE_SAFETY_SCREEN" | "POSITIVE_SAFETY_SCREEN";
                /** @enum {string} */
                reasonCode: "PHQ9_ITEM9_NEGATIVE" | "PHQ9_ITEM9_POSITIVE";
                policyVersion: string;
                guidanceCode: string;
                guidance: string;
            };
            resourceResolution: {
                /** @enum {string} */
                status: "AVAILABLE" | "PARTIAL" | "EMPTY" | "STALE" | "UNAVAILABLE";
                policyVersion: string;
                /** Format: date-time */
                resolvedAt: string;
            };
            resources: {
                /** Format: uuid */
                resourceId: string;
                contentVersion: string;
                /** Format: uuid */
                publicationId: string;
                /** @enum {string} */
                domain: "DEPRESSIVE_SYMPTOMS" | "ANXIETY_SYMPTOMS";
                /** @enum {string} */
                role: "PRIMARY" | "ADJUNCT";
                category: string;
                title: string;
                summary: string;
                /** Format: uri */
                externalUrl?: string | null;
            }[];
            provenance: {
                supportEvaluationPolicyVersion: string;
                assessmentResults: {
                    /** Format: uuid */
                    assessmentId: string;
                    /** @enum {string} */
                    instrument: "PHQ9" | "GAD7";
                    questionnaireVersion: string;
                    scoringVersion: string;
                    screeningLevel: string;
                }[];
            };
            phrasing: {
                /** @constant */
                source: "CARE_APPROVED_STANDARD";
                /** @enum {string} */
                status: "STANDARD" | "AI_UNAVAILABLE_FALLBACK";
            };
        };
        SupportGuideHistory: {
            items: components["schemas"]["SupportGuide"][];
            nextCursor?: string | null;
            hasMore: boolean;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            /** Format: uuid */
            correlationId: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem response. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSupportGuides: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest-first owner-scoped guide history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportGuideHistory"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    generateSupportGuide: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSupportGuideRequest"];
            };
        };
        responses: {
            /** @description New guide or deterministic replay for the same exact evidence. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportGuide"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getSupportGuide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supportGuideId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact immutable guide snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportGuide"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
