/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/community/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["browseCommunityFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCommunityPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get: operations["getCommunityPost"];
        put?: never;
        post?: never;
        delete: operations["deleteCommunityPost"];
        options?: never;
        head?: never;
        patch: operations["updateCommunityPost"];
        trace?: never;
    };
    "/api/v1/community/media/upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCommunityMediaUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/media/{mediaId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizeCommunityMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCommunityMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get: operations["listCommunityComments"];
        put?: never;
        post: operations["createCommunityComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCommunityComment"];
        options?: never;
        head?: never;
        patch: operations["updateCommunityComment"];
        trace?: never;
    };
    "/api/v1/community/posts/{postId}/reaction": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putCommunityReaction"];
        post?: never;
        delete: operations["deleteCommunityReaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/posts/{postId}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putCommunityBookmark"];
        post?: never;
        delete: operations["deleteCommunityBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCommunityReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/blocks/{communityProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityProfileId: components["parameters"]["CommunityProfileId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putCommunityBlock"];
        post?: never;
        delete: operations["deleteCommunityBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnCommunityProfile"];
        put: operations["putOwnCommunityProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCommunityTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/admin/moderation-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCommunityModerationCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/admin/moderation-cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCommunityModerationCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/community/admin/moderation-cases/{caseId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCommunityModerationAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        CommunityTopicCode: "MY_STORY" | "SMALL_MILESTONE" | "HELPFUL_REFLECTION" | "PEER_QUESTION" | "EXPERIENCE_SHARING" | "HELPFUL_RESOURCE";
        CommunityTopic: {
            code: components["schemas"]["CommunityTopicCode"];
            label: string;
            description: string;
        };
        CommunityAuthor: {
            /** Format: uuid */
            communityProfileId: string;
            displayName: string;
            /** @enum {string} */
            state: "ACTIVE" | "DELETED";
        };
        CommunityCounts: {
            comments: number;
            reactions: number;
        };
        CommunityMedia: {
            /** Format: uuid */
            mediaId: string;
            /** @enum {string} */
            type: "IMAGE" | "VIDEO";
            /** Format: uri */
            url: string;
            width: number | null;
            height: number | null;
            durationSeconds: number | null;
            altText: string | null;
        };
        CommunityPostSummary: {
            /** Format: uuid */
            postId: string;
            author: components["schemas"]["CommunityAuthor"];
            contentPreview: string;
            topics: components["schemas"]["CommunityTopicCode"][];
            media: components["schemas"]["CommunityMedia"][];
            /** @enum {string} */
            mediaAvailability: "NONE" | "READY" | "PARTIAL" | "UNAVAILABLE";
            counts: components["schemas"]["CommunityCounts"];
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityPostDetail: {
            /** Format: uuid */
            postId: string;
            author: components["schemas"]["CommunityAuthor"];
            content: string;
            topics: components["schemas"]["CommunityTopicCode"][];
            media: components["schemas"]["CommunityMedia"][];
            /** @enum {string} */
            mediaAvailability: "NONE" | "READY" | "PARTIAL" | "UNAVAILABLE";
            counts: components["schemas"]["CommunityCounts"];
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityFeedPage: {
            items: components["schemas"]["CommunityPostSummary"][];
            nextCursor: string | null;
            hasMore: boolean;
        };
        CreatePostRequest: {
            content: string;
            topics: components["schemas"]["CommunityTopicCode"][];
            mediaIds: string[];
        };
        UpdatePostRequest: components["schemas"]["CreatePostRequest"];
        /** @enum {string} */
        CommunityMediaState: "PENDING" | "PROCESSING" | "READY" | "REJECTED" | "DELETED" | "EXPIRED";
        CreateMediaUploadIntentRequest: {
            fileName: string;
            /** @enum {string} */
            mediaType: "IMAGE" | "VIDEO";
            mimeType: string;
            sizeBytes: number;
        };
        MediaUploadIntent: {
            /** Format: uuid */
            mediaId: string;
            /** @constant */
            state: "PENDING";
            /** Format: uri */
            uploadUrl: string;
            /** Format: date-time */
            expiresAt: string;
            requiredHeaders: {
                [key: string]: string;
            };
            version: number;
        };
        CommunityMediaRecord: {
            /** Format: uuid */
            mediaId: string;
            /** @enum {string} */
            mediaType: "IMAGE" | "VIDEO";
            state: components["schemas"]["CommunityMediaState"];
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        CommunityCommentState: "ACTIVE" | "OWNER_DELETED" | "MODERATION_HIDDEN" | "MODERATION_REMOVED";
        CommunityComment: {
            /** Format: uuid */
            commentId: string;
            /** Format: uuid */
            postId: string;
            /** Format: uuid */
            parentCommentId: string | null;
            author: components["schemas"]["CommunityAuthor"];
            content: string;
            state: components["schemas"]["CommunityCommentState"];
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CommunityCommentPage: {
            items: components["schemas"]["CommunityComment"][];
            nextCursor: string | null;
            hasMore: boolean;
        };
        CreateCommentRequest: {
            content: string;
            /** Format: uuid */
            parentCommentId: string | null;
        };
        UpdateCommentRequest: {
            content: string;
        };
        /** @enum {string} */
        SupportiveReaction: "SUPPORT" | "RELATE" | "THANK_YOU";
        PutReactionRequest: {
            reaction: components["schemas"]["SupportiveReaction"];
        };
        CommunityReaction: {
            /** Format: uuid */
            postId: string;
            reaction: components["schemas"]["SupportiveReaction"];
        };
        /** @enum {string} */
        ReportReason: "HARASSMENT" | "PRIVACY_OR_DOXXING" | "MEDICAL_MISINFORMATION" | "SELF_HARM_OR_CRISIS_CONCERN" | "SPAM" | "SEXUAL_OR_VIOLENT_CONTENT" | "OTHER";
        CreateReportRequest: {
            /** @enum {string} */
            targetType: "POST" | "COMMENT" | "COMMUNITY_PROFILE";
            /** Format: uuid */
            targetId: string;
            reason: components["schemas"]["ReportReason"];
            details: string | null;
        };
        PutCommunityProfileRequest: {
            displayName: string;
        };
        CommunityProfile: {
            /** Format: uuid */
            communityProfileId: string;
            displayName: string;
            /** @enum {string} */
            status: "ACTIVE" | "DELETED";
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        ModerationCaseState: "OPEN" | "IN_REVIEW" | "RESOLVED";
        /** @enum {string} */
        ModerationAction: "NO_ACTION" | "HIDE" | "REMOVE" | "RESTORE" | "RESTRICT_COMMUNITY_ACCESS";
        ModerationCase: {
            /** Format: uuid */
            caseId: string;
            /** @enum {string} */
            targetType: "POST" | "COMMENT" | "COMMUNITY_PROFILE";
            /** Format: uuid */
            targetId: string;
            state: components["schemas"]["ModerationCaseState"];
            reportReasons: components["schemas"]["ReportReason"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateModerationActionRequest: {
            action: components["schemas"]["ModerationAction"];
            reasonCode: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            /** Format: uuid */
            correlationId: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem response with a stable application code. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        PostId: string;
        CommentId: string;
        MediaId: string;
        CommunityProfileId: string;
        ModerationCaseId: string;
        IdempotencyKey: string;
        IfMatch: string;
        IfMatchOptional: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    browseCommunityFeed: {
        parameters: {
            query?: {
                topic?: components["schemas"]["CommunityTopicCode"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest-first active posts visible to the authenticated USER. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityFeedPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    createCommunityPost: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Created personal-story post. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityPostDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getCommunityPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active post visible to the authenticated USER. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityPostDetail"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteCommunityPost: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner post tombstoned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    updateCommunityPost: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description Updated owner post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityPostDetail"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    createCommunityMediaUploadIntent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaUploadIntentRequest"];
            };
        };
        responses: {
            /** @description Short-lived owner-scoped upload intent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaUploadIntent"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    finalizeCommunityMedia: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current processing state after provider verification. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityMediaRecord"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteCommunityMedia: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                mediaId: components["parameters"]["MediaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner media tombstoned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    listCommunityComments: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible comments in deterministic chronological order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityCommentPage"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createCommunityComment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description Created comment or reply. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityComment"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteCommunityComment: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner comment tombstoned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    updateCommunityComment: {
        parameters: {
            query?: never;
            header: {
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Updated owner comment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityComment"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    putCommunityReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutReactionRequest"];
            };
        };
        responses: {
            /** @description Current owner reaction. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityReaction"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteCommunityReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner reaction removed or already absent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    putCommunityBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner bookmark created or already present. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteCommunityBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner bookmark removed or already absent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createCommunityReport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Report accepted without exposing moderation state. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    putCommunityBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityProfileId: components["parameters"]["CommunityProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile blocked or already blocked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteCommunityBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                communityProfileId: components["parameters"]["CommunityProfileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile unblocked or already unblocked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getOwnCommunityProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated owner's Community display profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityProfile"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    putOwnCommunityProfile: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatchOptional"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutCommunityProfileRequest"];
            };
        };
        responses: {
            /** @description Current Community display profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityProfile"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    listCommunityTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Governed non-diagnostic Community topic catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunityTopic"][];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listCommunityModerationCases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded admin moderation queue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationCase"][];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getCommunityModerationCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: components["parameters"]["ModerationCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact moderation case visible to an authorized admin. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationCase"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    createCommunityModerationAction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                caseId: components["parameters"]["ModerationCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModerationActionRequest"];
            };
        };
        responses: {
            /** @description Audited moderation action. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationCase"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
}
