/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/service-credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's server-authoritative consultation-credit balance, distinct concurrent reservation capacity, and bounded ledger history. Reading provisions any missing credits for the current effective entitlement idempotently; clients must never derive mutable limits from the package name. */
        get: operations["getOwnServiceCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/entitlements/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's current server-authoritative service package. Absence of an effective paid or explicit demo projection returns FREE with DEFAULT_FREE provenance. */
        get: operations["getCurrentServiceEntitlement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnSpecialistProfile"];
        /** @description Creates a PENDING unsubmitted profile or replaces an existing PENDING profile draft. Editing a submitted profile clears submittedAt and removes it from the review queue until submitted again. */
        put: operations["saveOwnSpecialistProfileDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist-profile/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Places the complete PENDING profile in the administrator review queue. */
        post: operations["submitOwnSpecialistProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists the authenticated specialist's slots in a bounded UTC interval, including tombstones when requested. */
        get: operations["listOwnAvailabilitySlots"];
        put?: never;
        /** @description Publishes one exact future 60-minute online slot. Replaying the same Idempotency-Key with the same command returns the same slot identity and current state. */
        post: operations["publishOwnAvailabilitySlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability-slots/{slotId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slotId: components["parameters"]["AvailabilitySlotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Withdraws one owned future slot while retaining an auditable tombstone. */
        delete: operations["withdrawOwnAvailabilitySlot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookable-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists approved specialists' currently selectable exact 60-minute online slots. Disabled video slots and slots already held by an active appointment are excluded. */
        get: operations["listBookableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists the authenticated user's authoritative appointment snapshots, including request deadline and held credit identity. */
        get: operations["listOwnAppointments"];
        put?: never;
        /** @description Atomically creates a REQUESTED appointment for one exact slot after enforcing both available-credit and concurrent-reservation limits. When replacesAppointmentId is supplied, the active appointment and its held credit are atomically moved to a linked replacement request without temporarily consuming another reservation. Exact command replays return the original appointment. */
        post: operations["requestAppointment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns submitted PENDING profiles ordered by oldest submission first. */
        get: operations["listPendingSpecialistProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles/{specialistAccountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        get: operations["getSpecialistProfileForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles/{specialistAccountId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approves one submitted PENDING profile. Repeating against the current APPROVED version returns the same profile without another history row. */
        post: operations["approveSpecialistProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ServicePackage: "FREE" | "PLUS" | "PREMIUM";
        /** @enum {string} */
        EntitlementSource: "DEFAULT_FREE" | "DEMO" | "PAID";
        CurrentServiceEntitlement: {
            /** Format: uuid */
            accountId: string;
            packageCode: components["schemas"]["ServicePackage"];
            source: components["schemas"]["EntitlementSource"];
            /** @description Explicit demo identifier or future paid lifecycle reference; null only for DEFAULT_FREE. */
            sourceReference: string | null;
            /** Format: date-time */
            effectiveFrom: string | null;
            /**
             * Format: date-time
             * @description Exclusive entitlement end; null only for DEFAULT_FREE.
             */
            effectiveUntil: string | null;
            /** @constant */
            policyVersion: "service-entitlement-v1";
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            decidedAt: string;
        };
        /** @enum {string} */
        CreditSource: "DEFAULT_FREE" | "DEMO" | "PAID";
        /** @enum {string} */
        CreditLedgerEventType: "PROVISIONED" | "HELD" | "CONSUMED" | "RELEASED" | "FORFEITED";
        /** @enum {string} */
        ConsultationCreditPolicyVersion: "consultation-credit-v1" | "consultation-credit-v2";
        ServiceCreditBalance: {
            available: number;
            held: number;
            consumed: number;
            forfeited: number;
            total: number;
            releasedTransitions: number;
        };
        AppointmentReservationCapacity: {
            active: number;
            maximum: number;
            remaining: number;
        };
        ServiceCreditLedgerEvent: {
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            creditId: string;
            eventType: components["schemas"]["CreditLedgerEventType"];
            source: components["schemas"]["CreditSource"];
            packageCode: components["schemas"]["ServicePackage"];
            policyVersion: components["schemas"]["ConsultationCreditPolicyVersion"];
            /** Format: uuid */
            appointmentId: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
        ServiceCreditAccount: {
            /** Format: uuid */
            accountId: string;
            packageCode: components["schemas"]["ServicePackage"];
            source: components["schemas"]["CreditSource"];
            sourceReference: string | null;
            /** Format: date-time */
            periodStart: string | null;
            /** Format: date-time */
            periodEnd: string | null;
            policyVersion: components["schemas"]["ConsultationCreditPolicyVersion"];
            balance: components["schemas"]["ServiceCreditBalance"];
            reservationCapacity: components["schemas"]["AppointmentReservationCapacity"];
            history: components["schemas"]["ServiceCreditLedgerEvent"][];
            /** Format: date-time */
            generatedAt: string;
        };
        /** @enum {string} */
        SupportArea: "DEPRESSIVE_SYMPTOMS" | "ANXIETY_SYMPTOMS";
        /** @enum {string} */
        SpecialistApprovalStatus: "PENDING" | "APPROVED" | "REJECTED" | "SUSPENDED";
        /** @enum {string} */
        LanguageTag: "vi" | "en";
        SpecialistProfileRequest: {
            displayName: string;
            bio: string;
            supportAreas: components["schemas"]["SupportArea"][];
            languages: components["schemas"]["LanguageTag"][];
            yearsOfExperience: number;
            /** @description IANA timezone validated by the provider. */
            timezone: string;
        };
        SpecialistProfile: {
            /** Format: uuid */
            accountId: string;
            displayName: string;
            bio: string;
            supportAreas: components["schemas"]["SupportArea"][];
            languages: components["schemas"]["LanguageTag"][];
            yearsOfExperience: number;
            timezone: string;
            approvalStatus: components["schemas"]["SpecialistApprovalStatus"];
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            reviewedAt: string | null;
            /** Format: uuid */
            reviewedBy: string | null;
            decisionReasonCode: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        PendingSpecialistProfiles: {
            items: components["schemas"]["SpecialistProfile"][];
            count: number;
        };
        /** @enum {string} */
        AvailabilityModality: "IN_APP_CHAT" | "IN_APP_VIDEO";
        /** @enum {string} */
        AvailabilitySlotStatus: "ACTIVE" | "WITHDRAWN";
        /** @enum {string} */
        AvailabilityReadiness: "AVAILABLE" | "STARTED" | "WITHDRAWN" | "VIDEO_DISABLED";
        PublishAvailabilitySlotRequest: {
            /**
             * Format: date-time
             * @description Inclusive UTC start instant.
             */
            startAt: string;
            /**
             * Format: date-time
             * @description Exclusive UTC end instant exactly 60 minutes after startAt.
             */
            endAt: string;
            /** @description IANA timezone retained only for stable display. */
            timezone: string;
            modality: components["schemas"]["AvailabilityModality"];
        };
        AvailabilitySlot: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            timezone: string;
            modality: components["schemas"]["AvailabilityModality"];
            status: components["schemas"]["AvailabilitySlotStatus"];
            readiness: components["schemas"]["AvailabilityReadiness"];
            /** Format: date-time */
            withdrawnAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        AvailabilitySlotList: {
            items: components["schemas"]["AvailabilitySlot"][];
            count: number;
            /** Format: date-time */
            generatedAt: string;
            /** @description True only while the reviewed video capability/provider contract gate is enabled. */
            videoPublishingEnabled: boolean;
        };
        /** @enum {string} */
        AppointmentModality: "IN_APP_CHAT" | "IN_APP_VIDEO";
        RequestAppointment: {
            /** Format: uuid */
            slotId: string;
            modality: components["schemas"]["AppointmentModality"];
            /**
             * Format: uuid
             * @description Active user-owned appointment atomically replaced by this new request; omit for a normal request.
             */
            replacesAppointmentId?: string | null;
        };
        BookableSlot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            specialistAccountId: string;
            specialistDisplayName: string;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
            timezone: string;
            modality: components["schemas"]["AppointmentModality"];
        };
        BookableSlotList: {
            items: components["schemas"]["BookableSlot"][];
            count: number;
            /** Format: date-time */
            generatedAt: string;
            videoEnabled: boolean;
        };
        Appointment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            slotId: string;
            /** Format: uuid */
            specialistAccountId: string;
            specialistDisplayName: string;
            /** @enum {string} */
            status: "REQUESTED" | "CONFIRMED" | "IN_PROGRESS" | "REJECTED" | "EXPIRED" | "CANCELLED";
            modality: components["schemas"]["AppointmentModality"];
            /** Format: date-time */
            scheduledStartAt: string;
            /** Format: date-time */
            scheduledEndAt: string;
            timezone: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            decisionDeadlineAt: string;
            /** Format: uuid */
            heldCreditId: string;
            /** Format: uuid */
            replacesAppointmentId: string | null;
        };
        AppointmentList: {
            items: components["schemas"]["Appointment"][];
            count: number;
            /** Format: date-time */
            generatedAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            /** Format: uuid */
            correlationId: string;
            violations?: {
                field: string;
                code: string;
                message?: string;
            }[];
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description USER role or a current PLUS/PREMIUM entitlement is required (PAID_PLAN_REQUIRED). */
        AppointmentForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The selected slot or requested replacement appointment does not exist (APPOINTMENT_SLOT_NOT_FOUND or APPOINTMENT_REPLACEMENT_NOT_FOUND). */
        AppointmentSlotNotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Slot, modality, lead time, video capability, credit, reservation capacity, replacement state, concurrency, or idempotency prevents the request. */
        AppointmentConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Entitlement period conflicts with an already provisioned immutable credit period */
        CreditConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid body, path, or query parameter (VALIDATION_FAILED). */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is missing or invalid (UNAUTHENTICATED). */
        UnauthorizedProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Required SPECIALIST or ADMIN role is absent (CONSULTATION_ROLE_REQUIRED). */
        ForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The entitlement lookup requires an authenticated USER role (ENTITLEMENT_USER_REQUIRED). */
        EntitlementForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Specialist profile does not exist (SPECIALIST_PROFILE_NOT_FOUND). */
        NotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Profile state does not allow the requested operation. */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match does not equal the current profile version (SPECIALIST_PROFILE_VERSION_MISMATCH). */
        VersionProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match is required for the existing profile or command (PROFILE_VERSION_REQUIRED). */
        VersionRequiredProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Owned availability slot does not exist (AVAILABILITY_SLOT_NOT_FOUND). */
        AvailabilityNotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Slot overlaps active availability, is stale/withdrawn, reuses a key for another command, belongs to an unapproved specialist, or requests disabled video. */
        AvailabilityConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match does not equal the current slot version (AVAILABILITY_SLOT_VERSION_MISMATCH). */
        AvailabilityVersionProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match is required for withdrawal (AVAILABILITY_SLOT_VERSION_REQUIRED). */
        AvailabilityVersionRequiredProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        SpecialistAccountId: string;
        /** @description Omit only when creating the first profile; otherwise quote the current non-negative version. */
        OptionalIfMatch: string;
        /** @description Quoted current non-negative profile version. */
        RequiredIfMatch: string;
        AvailabilitySlotId: string;
        /** @description Printable caller key scoped to the authenticated specialist and retained with the slot outcome. */
        IdempotencyKey: string;
        /** @description Quoted current non-negative availability slot version. */
        AvailabilitySlotIfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted current profile version for If-Match. */
        ProfileETag: string;
        /** @description Quoted current availability slot version for If-Match. */
        AvailabilitySlotETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOwnServiceCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current plan, billing period, authoritative balance, and recent history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceCreditAccount"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["EntitlementForbiddenProblem"];
            409: components["responses"]["CreditConflictProblem"];
        };
    };
    getCurrentServiceEntitlement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current effective service-plan entitlement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentServiceEntitlement"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["EntitlementForbiddenProblem"];
        };
    };
    getOwnSpecialistProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current specialist-owned profile */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    saveOwnSpecialistProfileDraft: {
        parameters: {
            query?: never;
            header?: {
                /** @description Omit only when creating the first profile; otherwise quote the current non-negative version. */
                "If-Match"?: components["parameters"]["OptionalIfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistProfileRequest"];
            };
        };
        responses: {
            /** @description Existing draft replaced */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            /** @description Draft created */
            201: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
    submitOwnSpecialistProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted current non-negative profile version. */
                "If-Match": components["parameters"]["RequiredIfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile submitted or unchanged replay */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
    listOwnAvailabilitySlots: {
        parameters: {
            query?: {
                /** @description Inclusive UTC lower bound. Defaults to seven days before the request instant. */
                from?: string;
                /** @description Exclusive UTC upper bound. Defaults to ninety days after the request instant and may span at most 366 days from from. */
                to?: string;
                includeWithdrawn?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner-scoped availability and current modality capability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySlotList"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
        };
    };
    publishOwnAvailabilitySlot: {
        parameters: {
            query?: never;
            header: {
                /** @description Printable caller key scoped to the authenticated specialist and retained with the slot outcome. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishAvailabilitySlotRequest"];
            };
        };
        responses: {
            /** @description Slot published or the same slot aggregate returned for an exact replay */
            201: {
                headers: {
                    ETag: components["headers"]["AvailabilitySlotETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySlot"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            409: components["responses"]["AvailabilityConflictProblem"];
        };
    };
    withdrawOwnAvailabilitySlot: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted current non-negative availability slot version. */
                "If-Match": components["parameters"]["AvailabilitySlotIfMatch"];
            };
            path: {
                slotId: components["parameters"]["AvailabilitySlotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn slot tombstone */
            200: {
                headers: {
                    ETag: components["headers"]["AvailabilitySlotETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilitySlot"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["AvailabilityNotFoundProblem"];
            409: components["responses"]["AvailabilityConflictProblem"];
            412: components["responses"]["AvailabilityVersionProblem"];
            428: components["responses"]["AvailabilityVersionRequiredProblem"];
        };
    };
    listBookableSlots: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current selectable online slots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookableSlotList"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["EntitlementForbiddenProblem"];
        };
    };
    listOwnAppointments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User-owned appointment history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentList"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["EntitlementForbiddenProblem"];
        };
    };
    requestAppointment: {
        parameters: {
            query?: never;
            header: {
                /** @description Printable caller key scoped to the authenticated specialist and retained with the slot outcome. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestAppointment"];
            };
        };
        responses: {
            /** @description Appointment requested or exact replay returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Appointment"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["AppointmentForbiddenProblem"];
            404: components["responses"]["AppointmentSlotNotFoundProblem"];
            409: components["responses"]["AppointmentConflictProblem"];
        };
    };
    listPendingSpecialistProfiles: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending review queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingSpecialistProfiles"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
        };
    };
    getSpecialistProfileForAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational specialist profile detail */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    approveSpecialistProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted current non-negative profile version. */
                "If-Match": components["parameters"]["RequiredIfMatch"];
            };
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved profile */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
}
