/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/specialist-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnSpecialistProfile"];
        /** @description Creates a PENDING unsubmitted profile or replaces an existing PENDING profile draft. Editing a submitted profile clears submittedAt and removes it from the review queue until submitted again. */
        put: operations["saveOwnSpecialistProfileDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specialist-profile/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Places the complete PENDING profile in the administrator review queue. */
        post: operations["submitOwnSpecialistProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns submitted PENDING profiles ordered by oldest submission first. */
        get: operations["listPendingSpecialistProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles/{specialistAccountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        get: operations["getSpecialistProfileForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/specialist-profiles/{specialistAccountId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approves one submitted PENDING profile. Repeating against the current APPROVED version returns the same profile without another history row. */
        post: operations["approveSpecialistProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SupportArea: "DEPRESSIVE_SYMPTOMS" | "ANXIETY_SYMPTOMS";
        /** @enum {string} */
        SpecialistApprovalStatus: "PENDING" | "APPROVED" | "REJECTED" | "SUSPENDED";
        /** @enum {string} */
        LanguageTag: "vi" | "en";
        SpecialistProfileRequest: {
            displayName: string;
            bio: string;
            supportAreas: components["schemas"]["SupportArea"][];
            languages: components["schemas"]["LanguageTag"][];
            yearsOfExperience: number;
            /** @description IANA timezone validated by the provider. */
            timezone: string;
        };
        SpecialistProfile: {
            /** Format: uuid */
            accountId: string;
            displayName: string;
            bio: string;
            supportAreas: components["schemas"]["SupportArea"][];
            languages: components["schemas"]["LanguageTag"][];
            yearsOfExperience: number;
            timezone: string;
            approvalStatus: components["schemas"]["SpecialistApprovalStatus"];
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            reviewedAt: string | null;
            /** Format: uuid */
            reviewedBy: string | null;
            decisionReasonCode: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number;
        };
        PendingSpecialistProfiles: {
            items: components["schemas"]["SpecialistProfile"][];
            count: number;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            /** Format: uuid */
            correlationId: string;
            violations?: {
                field: string;
                code: string;
                message?: string;
            }[];
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Invalid body, path, or query parameter (VALIDATION_FAILED). */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is missing or invalid (UNAUTHENTICATED). */
        UnauthorizedProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Required SPECIALIST or ADMIN role is absent (CONSULTATION_ROLE_REQUIRED). */
        ForbiddenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Specialist profile does not exist (SPECIALIST_PROFILE_NOT_FOUND). */
        NotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Profile state does not allow the requested operation. */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match does not equal the current profile version (SPECIALIST_PROFILE_VERSION_MISMATCH). */
        VersionProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description If-Match is required for the existing profile or command (PROFILE_VERSION_REQUIRED). */
        VersionRequiredProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        SpecialistAccountId: string;
        /** @description Omit only when creating the first profile; otherwise quote the current non-negative version. */
        OptionalIfMatch: string;
        /** @description Quoted current non-negative profile version. */
        RequiredIfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Quoted current profile version for If-Match. */
        ProfileETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOwnSpecialistProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current specialist-owned profile */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    saveOwnSpecialistProfileDraft: {
        parameters: {
            query?: never;
            header?: {
                /** @description Omit only when creating the first profile; otherwise quote the current non-negative version. */
                "If-Match"?: components["parameters"]["OptionalIfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecialistProfileRequest"];
            };
        };
        responses: {
            /** @description Existing draft replaced */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            /** @description Draft created */
            201: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
    submitOwnSpecialistProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted current non-negative profile version. */
                "If-Match": components["parameters"]["RequiredIfMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile submitted or unchanged replay */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
    listPendingSpecialistProfiles: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending review queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingSpecialistProfiles"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
        };
    };
    getSpecialistProfileForAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational specialist profile detail */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    approveSpecialistProfile: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted current non-negative profile version. */
                "If-Match": components["parameters"]["RequiredIfMatch"];
            };
            path: {
                specialistAccountId: components["parameters"]["SpecialistAccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved profile */
            200: {
                headers: {
                    ETag: components["headers"]["ProfileETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialistProfile"];
                };
            };
            401: components["responses"]["UnauthorizedProblem"];
            403: components["responses"]["ForbiddenProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            412: components["responses"]["VersionProblem"];
            428: components["responses"]["VersionRequiredProblem"];
        };
    };
}
