/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — checks database connectivity */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active reviewed published self-help resources */
        get: operations["listResources"];
        put?: never;
        /** Create a new resource (Admin) */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/admin/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List resources in every lifecycle state (Admin) */
        get: operations["listAdminResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/admin/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get any resource lifecycle state (Admin) */
        get: operations["getAdminResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get an active reviewed resource for one locale */
        get: operations["getResource"];
        put?: never;
        post?: never;
        /** Delete a DRAFT resource (Admin) */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        /** Update a DRAFT resource (Admin) */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/api/v1/resources/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a reviewed DRAFT resource (blocked pending MB-251 policy approval) */
        post: operations["publishResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a PUBLISHED resource (Admin) */
        post: operations["archiveResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{id}/versions/{contentVersion}/eligibility-publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish immutable exact-version SupportPlan eligibility (Admin) */
        post: operations["publishResourceEligibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resources/{id}/versions/{contentVersion}/eligibility-publications/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an exact-version eligibility publication (Admin) */
        post: operations["withdrawResourceEligibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/resource-eligibility:resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve exact-version resource eligibility for Care in one bounded batch
         * @description Care forwards the authenticated USER bearer credential and correlation ID. Results preserve request order. A successful provider response never infers eligibility from resource type, review, or publication alone. Dependency uncertainty is represented by HTTP 503; Care maps it to UNAVAILABLE and commits no proposal mutation.
         */
        post: operations["resolveResourceEligibility"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety-directory/admin/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List directory records for administration */
        get: operations["listSafetyDirectoryEntriesForAdmin"];
        put?: never;
        /** Create an inactive unreviewed directory record */
        post: operations["createSafetyDirectoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety-directory/admin/entries/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace reviewed fields and invalidate prior review */
        patch: operations["updateSafetyDirectoryEntry"];
        trace?: never;
    };
    "/api/v1/safety-directory/admin/entries/{entryId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review, verify, and activate the exact directory version */
        post: operations["reviewSafetyDirectoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety-directory/admin/entries/{entryId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a directory record without deleting review history */
        post: operations["deactivateSafetyDirectoryEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety-directory:lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve active reviewed current records for one deliberate coarse area
         * @description Public read-only owner lookup used by Care. Manual text is matched only against reviewed area labels; no geocoding, proximity, or location sharing occurs.
         */
        post: operations["lookupSafetyDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SafetyDirectoryEntryType: "FACILITY" | "HOTLINE";
        /** @enum {string} */
        SafetyDirectoryCoverageLevel: "NATIONWIDE" | "PROVINCE" | "DISTRICT";
        SafetyDirectoryCoverage: {
            level: components["schemas"]["SafetyDirectoryCoverageLevel"];
            provinceCode: string | null;
            provinceName: string | null;
            districtCode: string | null;
            districtName: string | null;
        };
        SafetyDirectoryEntryWrite: {
            name: string;
            type: components["schemas"]["SafetyDirectoryEntryType"];
            phone: string;
            address: string | null;
            coverage: components["schemas"]["SafetyDirectoryCoverage"][];
            sourceName: string;
            sourceReference: string;
            /** Format: date-time */
            sourceRetrievedAt: string;
            sourceChecksum?: string | null;
        };
        /** @enum {string} */
        SafetyDirectoryReviewState: "UNREVIEWED" | "CURRENT" | "STALE" | "INACTIVE";
        SafetyDirectoryPublicEntry: {
            /** Format: uuid */
            directoryEntryId: string;
            name: string;
            type: components["schemas"]["SafetyDirectoryEntryType"];
            phone: string;
            address: string | null;
            coverage: components["schemas"]["SafetyDirectoryCoverage"][];
            sourceName: string;
            sourceReference: string;
            /** Format: date-time */
            reviewedAt: string;
            /** Format: date-time */
            verifiedAt: string;
        };
        SafetyDirectoryAdminEntry: components["schemas"]["SafetyDirectoryPublicEntry"] & ({
            /** Format: int64 */
            recordVersion: number;
            active: boolean;
            reviewState: components["schemas"]["SafetyDirectoryReviewState"];
            /** Format: uuid */
            reviewedBy: string | null;
            /** Format: uuid */
            verifiedBy: string | null;
            /** Format: date-time */
            sourceRetrievedAt: string;
            sourceChecksum: string | null;
            readonly seedKey: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        } & {
            [key: string]: unknown;
        });
        SafetyDirectoryLookupRequest: {
            provinceCode?: string;
            districtCode?: string;
            manualLocation?: string;
        } & (unknown | unknown);
        /** @enum {string} */
        SafetyDirectoryLookupState: "RESULTS" | "EMPTY" | "INVALID_AREA";
        SafetyDirectoryLookupResponse: {
            state: components["schemas"]["SafetyDirectoryLookupState"];
            /** @constant */
            wording: "Cơ sở trong khu vực đã chọn";
            resolvedProvinceCode: string | null;
            resolvedDistrictCode: string | null;
            entries: components["schemas"]["SafetyDirectoryPublicEntry"][];
        } & {
            [key: string]: unknown;
        };
        LiveResponse: {
            /** @example ok */
            status: string;
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            db: "connected" | "disconnected";
        };
        ProblemDetails: {
            /**
             * Format: uri
             * @example https://mentalbridge.io/errors/RESOURCE_NOT_FOUND
             */
            type: string;
            /** @example Resource not found */
            title: string;
            /** @example 404 */
            status: number;
            /** @example RESOURCE_NOT_FOUND */
            code: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            correlationId?: string | null;
            /**
             * @example [
             *       {
             *         "field": "title",
             *         "message": "Title is required"
             *       }
             *     ]
             */
            fieldViolations?: {
                field?: string;
                message?: string;
            }[];
        };
        /** @enum {string} */
        ResourceCategory: "BREATHING" | "MEDITATION" | "ARTICLE" | "VIDEO" | "JOURNALING" | "COMMUNITY";
        /** @enum {string} */
        ResourceStatus: "DRAFT" | "PUBLISHED" | "ARCHIVED";
        ResourceSummary: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["ResourceCategory"];
            locale: string;
            title: string;
            summary: string;
            externalUrl?: string | null;
            /** @description Simple accountable source label for catalogue cards. */
            sourceOrganization?: string | null;
            status: components["schemas"]["ResourceStatus"];
            /** Format: date-time */
            reviewedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PublicResourceDetail: components["schemas"]["ResourceSummary"] & {
            contentBody: string | null;
            sourceTitle?: string | null;
            /** Format: uri */
            sourceUrl?: string | null;
            sourceReviewNote?: string | null;
            /** Format: date-time */
            effectiveAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
        };
        AdminResourceDetail: components["schemas"]["PublicResourceDetail"] & {
            /** Format: uuid */
            reviewedBy: string | null;
            version: number;
        };
        ResourceListResponse: {
            data: components["schemas"]["ResourceSummary"][];
            count: number;
            /**
             * Format: uuid
             * @description Cursor for the next page; absent when no more results.
             */
            nextCursor?: string;
            /**
             * @description Present only when Content/Notification is unavailable. No hotline number or emergency dispatch claim is included.
             * @enum {string}
             */
            fallback?: "unavailable";
            /** @description Neutral fallback message when fallback is unavailable. */
            message?: string;
        };
        CreateResourceRequest: {
            category: components["schemas"]["ResourceCategory"];
            /** @default vi-VN */
            locale: string;
            title: string;
            summary: string;
            contentBody?: string | null;
            /**
             * Format: uri
             * @description VIDEO resources require a verified HTTPS YouTube URL.
             */
            externalUrl?: string | null;
            sourceOrganization?: string | null;
            sourceTitle?: string | null;
            /** Format: uri */
            sourceUrl?: string | null;
            sourceReviewNote?: string | null;
            /** Format: date-time */
            effectiveAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        UpdateResourceRequest: {
            locale?: string;
            title?: string;
            summary?: string;
            contentBody?: string | null;
            /**
             * Format: uri
             * @description VIDEO resources require a verified HTTPS YouTube URL.
             */
            externalUrl?: string | null;
            sourceOrganization?: string | null;
            sourceTitle?: string | null;
            /** Format: uri */
            sourceUrl?: string | null;
            sourceReviewNote?: string | null;
            /** Format: date-time */
            effectiveAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        /** @enum {string} */
        EligibilityPolicyVersion: "content-eligibility-v1";
        /**
         * @description V1 screening domains only; GENERAL_WELLBEING and BOTH_SCREENED_DOMAINS are invalid.
         * @enum {string}
         */
        ScreeningDomain: "DEPRESSIVE_SYMPTOMS" | "ANXIETY_SYMPTOMS";
        /** @enum {string} */
        EligibilityRole: "PRIMARY" | "ADJUNCT";
        /**
         * @description PRIMARY_OR_ADJUNCT is valid only for an optional SupportPlan slot.
         * @enum {string}
         */
        RequiredEligibilityRole: "PRIMARY" | "PRIMARY_OR_ADJUNCT";
        /** @enum {string} */
        ScreeningInstrument: "PHQ_9" | "GAD_7";
        /** @enum {string} */
        ScreeningLevel: "MINIMAL" | "MILD" | "MODERATE" | "MODERATELY_SEVERE" | "SEVERE";
        /** @enum {string} */
        SupportTier: "SELF_GUIDED_SUPPORT" | "PROFESSIONAL_SUPPORT_RECOMMENDED" | "SAFETY_FOLLOW_UP_RECOMMENDED";
        /** @enum {string} */
        EligibilityPublicationState: "PUBLISHED" | "WITHDRAWN";
        EligibilityDeclaration: {
            targetDomain: components["schemas"]["ScreeningDomain"];
            role: components["schemas"]["EligibilityRole"];
            instrument: components["schemas"]["ScreeningInstrument"];
            screeningLevels: components["schemas"]["ScreeningLevel"][];
            supportTiers: components["schemas"]["SupportTier"][];
        };
        PublishResourceEligibilityRequest: {
            policyVersion: components["schemas"]["EligibilityPolicyVersion"];
            locale: string;
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            declarations: components["schemas"]["EligibilityDeclaration"][];
        };
        WithdrawResourceEligibilityRequest: {
            policyVersion: components["schemas"]["EligibilityPolicyVersion"];
            /** @enum {string} */
            reasonCode: "CONTENT_WITHDRAWN" | "POLICY_WITHDRAWN" | "SUPERSEDED";
        };
        ResourceEligibilityPublication: {
            /** Format: uuid */
            publicationId: string;
            /** Format: uuid */
            resourceId: string;
            contentVersion: string;
            policyVersion: components["schemas"]["EligibilityPolicyVersion"];
            locale: string;
            state: components["schemas"]["EligibilityPublicationState"];
            /** Format: date-time */
            effectiveAt: string;
            /** Format: date-time */
            expiresAt?: string | null;
            declarations: components["schemas"]["EligibilityDeclaration"][];
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            withdrawnAt?: string | null;
            /** @enum {string|null} */
            withdrawalReasonCode?: "CONTENT_WITHDRAWN" | "POLICY_WITHDRAWN" | "SUPERSEDED" | null;
        } & {
            [key: string]: unknown;
        };
        ResourceEligibilityQuery: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            resourceId: string;
            contentVersion: string;
            targetDomain: components["schemas"]["ScreeningDomain"];
            requiredRole: components["schemas"]["RequiredEligibilityRole"];
            instrument: components["schemas"]["ScreeningInstrument"];
            screeningLevel: components["schemas"]["ScreeningLevel"];
            supportTier: components["schemas"]["SupportTier"];
            locale: string;
        };
        ResourceEligibilityBatchRequest: {
            requests: components["schemas"]["ResourceEligibilityQuery"][];
        };
        /**
         * @description UNAVAILABLE is a Care fail-closed fallback and is never emitted in a provider HTTP 200 response.
         * @enum {string}
         */
        ResourceEligibilityOutcome: "ELIGIBLE" | "INELIGIBLE" | "STALE" | "WITHDRAWN" | "NOT_FOUND" | "UNAVAILABLE";
        /** @enum {string} */
        ResourceEligibilityReasonCode: "ELIGIBLE_MATCH" | "RESOURCE_NOT_FOUND" | "CONTENT_VERSION_STALE" | "NO_ELIGIBILITY_PUBLICATION" | "DOMAIN_OR_PATHWAY_NOT_ELIGIBLE" | "PRIMARY_REQUIRED" | "NOT_YET_EFFECTIVE" | "EFFECTIVE_WINDOW_ENDED" | "RESOURCE_ARCHIVED" | "RESOURCE_NOT_PUBLISHED" | "LOCALE_MISMATCH" | "ELIGIBILITY_WITHDRAWN" | "DEPENDENCY_UNAVAILABLE";
        ResourceEligibilityResult: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            resourceId: string;
            contentVersion: string;
            outcome: components["schemas"]["ResourceEligibilityOutcome"];
            reasonCode: components["schemas"]["ResourceEligibilityReasonCode"];
            role?: components["schemas"]["EligibilityRole"] | null;
            /** Format: uuid */
            publicationId?: string | null;
            /** @description Present only for an eligible exact version so Care can persist the approved display snapshot. */
            category?: components["schemas"]["ResourceCategory"] | null;
            title?: string | null;
            summary?: string | null;
            /** Format: uri */
            externalUrl?: string | null;
        } & {
            [key: string]: unknown;
        };
        ResourceEligibilityBatchResponse: {
            policyVersion: components["schemas"]["EligibilityPolicyVersion"];
            /** Format: date-time */
            resolvedAt: string;
            results: components["schemas"]["ResourceEligibilityResult"][];
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Authentication is required or the credential is invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authenticated actor is not an administrator */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource administration is temporarily unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The actor reused an idempotency key with a different create payload */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Publish is unavailable until an approved MB-251 review decision is recorded */
        ReviewApprovalRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://mentalbridge.io/errors/RESOURCE_NOT_FOUND",
                 *       "title": "Resource not found",
                 *       "status": 404,
                 *       "code": "RESOURCE_NOT_FOUND",
                 *       "correlationId": "123e4567-e89b-12d3-a456-426614174000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description State conflict or optimistic lock failure */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://mentalbridge.io/errors/INVALID_STATE_TRANSITION",
                 *       "title": "Cannot modify published resource",
                 *       "status": 409,
                 *       "code": "INVALID_STATE_TRANSITION",
                 *       "correlationId": "123e4567-e89b-12d3-a456-426614174000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://mentalbridge.io/errors/VALIDATION_ERROR",
                 *       "title": "Validation failed",
                 *       "status": 422,
                 *       "code": "VALIDATION_ERROR",
                 *       "correlationId": "123e4567-e89b-12d3-a456-426614174000",
                 *       "fieldViolations": [
                 *         {
                 *           "field": "title",
                 *           "message": "Title is required"
                 *         },
                 *         {
                 *           "field": "category",
                 *           "message": "Invalid category"
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Invalid query parameter */
        RequestRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://mentalbridge.io/errors/REQUEST_REJECTED",
                 *       "title": "Request rejected",
                 *       "status": 400,
                 *       "code": "REQUEST_REJECTED",
                 *       "correlationId": "123e4567-e89b-12d3-a456-426614174000"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        ResourceId: string;
        /** @description Opaque key reused only for an unchanged logical create request by this actor. */
        IdempotencyKey: string;
        Locale: string;
        Category: components["schemas"]["ResourceCategory"];
        Limit: number;
        Cursor: string;
        /** @description Exact non-negative 64-bit content version encoded as a JSON-safe decimal string. */
        ContentVersion: string;
        DirectoryEntryId: string;
        DirectoryVersion: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "db": "connected"
                     *     }
                     */
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Service unavailable — database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://mentalbridge.io/errors/DEPENDENCY_UNAVAILABLE",
                     *       "title": "Dependency unavailable",
                     *       "status": 503,
                     *       "code": "DEPENDENCY_UNAVAILABLE"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: {
                locale?: string;
                category?: components["schemas"]["ResourceCategory"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published reviewed resources. Returns empty array when none match. Returns fallback: unavailable with neutral message when service is unreachable. No hotline number or emergency dispatch claim is included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceListResponse"];
                };
            };
            400: components["responses"]["RequestRejected"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque key reused only for an unchanged logical create request by this actor. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResourceRequest"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "123e4567-e89b-12d3-a456-426614174000",
                     *       "category": "BREATHING",
                     *       "locale": "vi-VN",
                     *       "title": "Kỹ thuật thở 4-7-8",
                     *       "summary": "Kỹ thuật thở giúp giảm căng thẳng và lo âu",
                     *       "externalUrl": null,
                     *       "status": "DRAFT",
                     *       "reviewedAt": null,
                     *       "createdAt": "2024-01-15T10:00:00Z",
                     *       "updatedAt": "2024-01-15T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ResourceSummary"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAdminResources: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
                category?: components["parameters"]["Category"];
                status?: components["schemas"]["ResourceStatus"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of admin-visible resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceListResponse"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getAdminResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full admin resource detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminResourceDetail"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getResource: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicResourceDetail"];
                };
            };
            400: components["responses"]["RequestRejected"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteResource: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateResource: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description Updated resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    publishResource: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["ReviewApprovalRequired"];
        };
    };
    archiveResource: {
        parameters: {
            query: {
                version: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource archived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    publishResourceEligibility: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque key reused only for an unchanged logical create request by this actor. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
                /** @description Exact non-negative 64-bit content version encoded as a JSON-safe decimal string. */
                contentVersion: components["parameters"]["ContentVersion"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishResourceEligibilityRequest"];
            };
        };
        responses: {
            /** @description Immutable eligibility publication created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEligibilityPublication"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    withdrawResourceEligibility: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque key reused only for an unchanged logical create request by this actor. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ResourceId"];
                /** @description Exact non-negative 64-bit content version encoded as a JSON-safe decimal string. */
                contentVersion: components["parameters"]["ContentVersion"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawResourceEligibilityRequest"];
            };
        };
        responses: {
            /** @description Eligibility publication withdrawn or an identical command replayed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEligibilityPublication"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    resolveResourceEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEligibilityBatchRequest"];
            };
        };
        responses: {
            /** @description Deterministic exact-version eligibility outcomes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEligibilityBatchResponse"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listSafetyDirectoryEntriesForAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All current administrative records, including inactive and stale entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryAdminEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createSafetyDirectoryEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque key reused only for an unchanged logical create request by this actor. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyDirectoryEntryWrite"];
            };
        };
        responses: {
            /** @description Inactive unreviewed record created or identical command replayed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryAdminEntry"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["IdempotencyConflict"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateSafetyDirectoryEntry: {
        parameters: {
            query: {
                version: components["parameters"]["DirectoryVersion"];
            };
            header?: never;
            path: {
                entryId: components["parameters"]["DirectoryEntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyDirectoryEntryWrite"];
            };
        };
        responses: {
            /** @description Record updated, deactivated, and returned to unreviewed state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryAdminEntry"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reviewSafetyDirectoryEntry: {
        parameters: {
            query: {
                version: components["parameters"]["DirectoryVersion"];
            };
            header?: never;
            path: {
                entryId: components["parameters"]["DirectoryEntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact record version reviewed, verified with server time, and activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryAdminEntry"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deactivateSafetyDirectoryEntry: {
        parameters: {
            query: {
                version: components["parameters"]["DirectoryVersion"];
            };
            header?: never;
            path: {
                entryId: components["parameters"]["DirectoryEntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record is inactive; repeating against the current inactive version is safe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryAdminEntry"];
                };
            };
            400: components["responses"]["RequestRejected"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    lookupSafetyDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyDirectoryLookupRequest"];
            };
        };
        responses: {
            /** @description Current records or an explicit empty/invalid-area outcome */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyDirectoryLookupResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
