/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready for its current baseline dependencies. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Owned MongoDB is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics endpoint. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List private journal entries with bounded cursor pagination. */
        get: operations["listJournalEntries"];
        put?: never;
        /** Create a private journal entry. */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{journalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one private journal entry. */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        /** Tombstone a private journal entry. */
        delete: operations["deleteJournalEntry"];
        options?: never;
        head?: never;
        /** Revise an existing journal entry. */
        patch: operations["reviseJournalEntry"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
            /** @enum {string} */
            environment: "development" | "test" | "production";
        };
        CreateJournalRequest: {
            /**
             * Format: uuid
             * @description Client-generated entry ID used for idempotency and offline drafts.
             */
            clientEntryId: string;
            /** Format: date-time */
            occurredAt: string;
            content: components["schemas"]["JournalContentInput"];
            tags?: string[];
        };
        ReviseJournalRequest: {
            content: components["schemas"]["JournalContentInput"];
            tags?: string[];
        };
        JournalContentInput: {
            /** @description Plaintext is accepted only at the API boundary and must not be logged or indexed. */
            text: string;
        };
        JournalEntryMetadata: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerAccountId: string;
            currentRevision: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            deleted: boolean;
            tags?: string[];
            encryption: components["schemas"]["EncryptionMetadata"];
            /** @enum {string} */
            analysisState: "not_requested" | "current" | "stale";
        };
        JournalEntry: components["schemas"]["JournalEntryMetadata"] & {
            content: components["schemas"]["JournalContent"];
        };
        JournalEntrySummary: components["schemas"]["JournalEntryMetadata"] & {
            content: components["schemas"]["JournalContentSummary"];
        };
        JournalContent: {
            /** @description Decrypted only after owner authorization and never logged or persisted as plaintext. */
            text: string;
            byteLength: number;
        };
        JournalContentSummary: {
            /** @description Derived after an authorized decrypt for this response and never stored or indexed as plaintext. */
            preview: string;
            byteLength: number;
        };
        EncryptionMetadata: {
            /** @enum {string} */
            algorithm: "AES-256-GCM";
            keyId: string;
            /** Format: date-time */
            encryptedAt: string;
        };
        JournalTombstone: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerAccountId: string;
            /** @enum {boolean} */
            deleted: true;
            /** Format: date-time */
            deletedAt: string;
        };
        JournalListResponse: {
            items: components["schemas"]["JournalEntrySummary"][];
            page: {
                limit: number;
                nextCursor?: string;
                hasMore: boolean;
            };
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: string;
            detail?: string;
            correlationId: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Journal entry was not found for the authenticated owner. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Idempotency conflict or duplicate mutation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Revision precondition failed. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        JournalId: string;
        /** @description Stable key for safe client retries of journal mutations. */
        IdempotencyKey: string;
        /** @description Current revision number expected by the client. */
        IfMatchRevision: number;
        CorrelationId: string;
        Limit: number;
        /** @description Opaque cursor returned by the previous list response. */
        Cursor: string;
        IncludeDeleted: boolean;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation ID used in request logs. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listJournalEntries: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous list response. */
                cursor?: components["parameters"]["Cursor"];
                includeDeleted?: components["parameters"]["IncludeDeleted"];
            };
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded page of journal entries. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJournalRequest"];
            };
        };
        responses: {
            /** @description Journal entry created. */
            201: {
                headers: {
                    /** @description URL of the created journal entry. */
                    Location?: string;
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journal entry found. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journal entry tombstoned. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalTombstone"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reviseJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Current revision number expected by the client. */
                "If-Match-Revision": components["parameters"]["IfMatchRevision"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseJournalRequest"];
            };
        };
        responses: {
            /** @description Journal entry revised and current analysis invalidated. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
}
