/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready for its current baseline dependencies. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Owned MongoDB is unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics endpoint. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emotion-check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's self-reported emotion history. */
        get: operations["listEmotionCheckIns"];
        put?: never;
        /** Record the authenticated user's check-in for the current local day. */
        post: operations["createEmotionCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emotion-check-ins/{localDate}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reload one owned check-in by its recorded local day. */
        get: operations["getEmotionCheckIn"];
        put?: never;
        post?: never;
        /** Delete the encrypted emotion payload and tombstone the local day. */
        delete: operations["deleteEmotionCheckIn"];
        options?: never;
        head?: never;
        /** Update the owned check-in while its stored local day is current. */
        patch: operations["updateEmotionCheckIn"];
        trace?: never;
    };
    "/api/v1/emotion-check-in-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return a note-free minimized projection for consented AI reflection.
         * @description Reminder composition is deliberately unavailable until a separate reminder consent contract is accepted.
         */
        get: operations["getEmotionCheckInConsumerContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List private journal entries with bounded cursor pagination. */
        get: operations["listJournalEntries"];
        put?: never;
        /** Create a private journal entry. */
        post: operations["createJournalEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/journals/{journalId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one private journal entry. */
        get: operations["getJournalEntry"];
        put?: never;
        post?: never;
        /** Tombstone a private journal entry. */
        delete: operations["deleteJournalEntry"];
        options?: never;
        head?: never;
        /** Revise an existing journal entry. */
        patch: operations["reviseJournalEntry"];
        trace?: never;
    };
    "/api/v1/journals/{journalId}/revisions/{revision}/analysis-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request analysis of one exact owned journal revision. */
        post: operations["createExactRevisionAnalysisJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an owned analysis job and its normalized result. */
        get: operations["getOwnAnalysisJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Self-selected, non-clinical label shared with Journal authoring.
         * @enum {string}
         */
        Emotion: "GREAT" | "GOOD" | "OKAY" | "LOW" | "VERY_LOW";
        EmotionCheckInValue: {
            emotion: components["schemas"]["Emotion"];
            /** @description Strength of the selected feeling, not wellness, severity, diagnosis, or recovery. */
            intensity: number;
            /** @description Optional private free text; encrypted at rest and excluded from consumer projections, logs, and events. */
            note?: string | null;
        };
        CreateEmotionCheckInRequest: components["schemas"]["EmotionCheckInValue"] & {
            /** Format: date */
            localDate: string;
            /** @description IANA timezone; localDate must equal the server acceptance time in this zone. */
            timezone: string;
        };
        EmotionCheckIn: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            localDate: string;
            timezone: string;
            emotion: components["schemas"]["Emotion"];
            intensity: number;
            note: string | null;
            /** @constant */
            sourceLabel: "SELF_REPORTED_EMOTION";
            /** @constant */
            clinicalUse: "NOT_A_DIAGNOSIS_OR_SAFETY_CLASSIFIER";
            revision: number;
            /** Format: date-time */
            recordedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EmotionCheckInList: {
            items: components["schemas"]["EmotionCheckIn"][];
            page: {
                limit: number;
                hasMore: boolean;
                /** Format: date */
                nextBefore?: string;
            };
            /** @constant */
            label: "SELF_REPORTED_EMOTION";
            /** @constant */
            interpretation: "NOT_DIAGNOSIS_OR_RECOVERY";
        };
        EmotionCheckInTombstone: {
            /** Format: date */
            localDate: string;
            /** @constant */
            deleted: true;
            /** Format: date-time */
            deletedAt: string;
        };
        EmotionCheckInConsumerItem: {
            /** Format: date */
            localDate: string;
            timezone: string;
            emotion: components["schemas"]["Emotion"];
            intensity: number;
            /** @constant */
            sourceLabel: "SELF_REPORTED_EMOTION";
            revision: number;
            /** Format: date-time */
            recordedAt: string;
        };
        EmotionCheckInConsumerContext: {
            /** @constant */
            purpose: "AI_REFLECTION";
            consent: {
                /** @constant */
                type: "AI_PROCESSING";
                policyVersion: string | null;
            };
            items: components["schemas"]["EmotionCheckInConsumerItem"][];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            service: string;
            /** @enum {string} */
            environment: "development" | "test" | "production";
        };
        CreateJournalRequest: {
            /**
             * Format: uuid
             * @description Client-generated entry ID used for idempotency and offline drafts.
             */
            clientEntryId: string;
            /** Format: date-time */
            occurredAt: string;
            content: components["schemas"]["JournalContentInput"];
            /** @description Optional during the compatibility window; new MentalBridge editors require an explicit user selection. */
            mood?: components["schemas"]["JournalMood"];
            tags?: string[];
        };
        ReviseJournalRequest: {
            content: components["schemas"]["JournalContentInput"];
            /** @description When omitted by an older client, the current revision mood is preserved. */
            mood?: components["schemas"]["JournalMood"];
            tags?: string[];
        };
        JournalContentInput: {
            /** @description Non-blank plaintext is accepted only at the API boundary and must not be logged or indexed. */
            text: string;
        };
        /**
         * @description User-selected reflection label; it is not a clinical score and the emoji presentation is client-owned.
         * @enum {string}
         */
        JournalMood: "GREAT" | "GOOD" | "OKAY" | "LOW" | "VERY_LOW";
        JournalEntryMetadata: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerAccountId: string;
            currentRevision: number;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            deleted: boolean;
            tags: string[];
            /** @description Mood stored with the current encrypted revision; null only for entries written by compatible legacy clients. */
            mood: components["schemas"]["JournalMood"] | null;
            encryption: components["schemas"]["EncryptionMetadata"];
            /** @enum {string} */
            analysisState: "not_requested" | "current" | "stale";
        };
        JournalEntry: components["schemas"]["JournalEntryMetadata"] & {
            content: components["schemas"]["JournalContent"];
        };
        JournalEntrySummary: components["schemas"]["JournalEntryMetadata"] & {
            content: components["schemas"]["JournalContentSummary"];
        };
        JournalContent: {
            /** @description Decrypted only after owner authorization and never logged or persisted as plaintext. */
            text: string;
            byteLength: number;
        };
        JournalContentSummary: {
            /** @description Derived after an authorized decrypt for this response and never stored or indexed as plaintext. */
            preview: string;
            byteLength: number;
        };
        EncryptionMetadata: {
            /** @enum {string} */
            algorithm: "AES-256-GCM";
            keyId: string;
            /** Format: date-time */
            encryptedAt: string;
        };
        JournalTombstone: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ownerAccountId: string;
            /** @enum {boolean} */
            deleted: true;
            /** Format: date-time */
            deletedAt: string;
        };
        JournalListResponse: {
            items: components["schemas"]["JournalEntrySummary"][];
            page: {
                limit: number;
                nextCursor?: string;
                hasMore: boolean;
            };
        };
        AnalysisJob: {
            /** Format: uuid */
            jobId: string;
            /** Format: uuid */
            journalId: string;
            journalRevision: number;
            /** @enum {string} */
            status: "RUNNING" | "SUCCEEDED" | "FAILED";
            attemptCount: number;
            terminalReason?: components["schemas"]["AnalysisTerminalReason"] | null;
            result?: components["schemas"]["NormalizedAnalysisResult"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        /** @enum {string} */
        AnalysisTerminalReason: "CONSENT_REQUIRED" | "CONSENT_REVOKED" | "CONSENT_UNAVAILABLE" | "AUTHORIZATION_CONTEXT_LOST" | "REVISION_STALE" | "JOURNAL_DELETED" | "PROVIDER_TIMEOUT" | "PROVIDER_UNAVAILABLE" | "INVALID_PROVIDER_RESULT" | "INTERNAL_ERROR";
        NormalizedAnalysisResult: {
            summary?: string;
            contextSignals: string[];
            emotionIndicators: string[];
            themes: string[];
            preferenceSignals: string[];
            barrierSignals: string[];
            sentiment?: string;
            modelConfidence?: number;
            /** @enum {string} */
            suggestedAction: "NONE" | "OFFER_RESOURCE_EXPLANATION" | "GUIDE_APPROVED_ACTIVITY" | "REQUEST_ALLOWED_ALTERNATIVE" | "REQUEST_PLAN_REVIEW" | "OPEN_PROFESSIONAL_SUPPORT" | "OPEN_SAFETY_GUIDANCE";
            /** @constant */
            provider: "DETERMINISTIC_FAKE";
            /** @constant */
            model: "deterministic-reflection-v1";
            /** @constant */
            promptVersion: "exact-revision-v1";
            /** @constant */
            schemaVersion: 1;
            /** Format: date-time */
            createdAt: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: string;
            detail?: string;
            correlationId: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Current consent does not authorize this minimized consumer projection. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Journal entry was not found for the authenticated owner. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Idempotency conflict, duplicate mutation, or journal revision limit reached. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Revision precondition failed. */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Care consent could not be verified; no provider call was made. */
        DependencyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Calendar day computed in the IANA timezone stored at creation. */
        LocalDate: string;
        EmotionLimit: number;
        /** @description Exclusive newest-first history cursor. */
        BeforeLocalDate: string;
        JournalId: string;
        JournalRevision: number;
        AnalysisJobId: string;
        /** @description Stable key for safe client retries of journal mutations. */
        IdempotencyKey: string;
        /** @description Current revision number expected by the client. */
        IfMatchRevision: number;
        CorrelationId: string;
        Limit: number;
        /** @description Opaque cursor returned by the previous list response. */
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation ID used in request logs. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEmotionCheckIns: {
        parameters: {
            query?: {
                limit?: components["parameters"]["EmotionLimit"];
                /** @description Exclusive newest-first history cursor. */
                before?: components["parameters"]["BeforeLocalDate"];
            };
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A bounded, newest-first history page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckInList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    createEmotionCheckIn: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmotionCheckInRequest"];
            };
        };
        responses: {
            /** @description Check-in created, or an exact create retry replayed. */
            201: {
                headers: {
                    Location?: string;
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckIn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getEmotionCheckIn: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                /** @description Calendar day computed in the IANA timezone stored at creation. */
                localDate: components["parameters"]["LocalDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The owned active check-in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckIn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    deleteEmotionCheckIn: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                /** @description Calendar day computed in the IANA timezone stored at creation. */
                localDate: components["parameters"]["LocalDate"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The encrypted payload was removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckInTombstone"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    updateEmotionCheckIn: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Current revision number expected by the client. */
                "If-Match-Revision": components["parameters"]["IfMatchRevision"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                /** @description Calendar day computed in the IANA timezone stored at creation. */
                localDate: components["parameters"]["LocalDate"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmotionCheckInValue"];
            };
        };
        responses: {
            /** @description Check-in updated, or an exact update retry replayed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckIn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getEmotionCheckInConsumerContext: {
        parameters: {
            query: {
                purpose: "AI_REFLECTION";
                limit?: number;
            };
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current Care consent was verified and only minimized fields are returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionCheckInConsumerContext"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    listJournalEntries: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque cursor returned by the previous list response. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded page of journal entries. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJournalRequest"];
            };
        };
        responses: {
            /** @description Journal entry created. */
            201: {
                headers: {
                    /** @description URL of the created journal entry. */
                    Location?: string;
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getJournalEntry: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journal entry found. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Journal entry tombstoned. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalTombstone"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reviseJournalEntry: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Current revision number expected by the client. */
                "If-Match-Revision": components["parameters"]["IfMatchRevision"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviseJournalRequest"];
            };
        };
        responses: {
            /** @description Journal entry revised and current analysis invalidated. */
            200: {
                headers: {
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["PreconditionFailed"];
        };
    };
    createExactRevisionAnalysisJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Stable key for safe client retries of journal mutations. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                journalId: components["parameters"]["JournalId"];
                revision: components["parameters"]["JournalRevision"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The idempotent asynchronous job was accepted. */
            202: {
                headers: {
                    Location?: string;
                    "x-correlation-id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["DependencyUnavailable"];
        };
    };
    getOwnAnalysisJob: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: components["parameters"]["CorrelationId"];
            };
            path: {
                jobId: components["parameters"]["AnalysisJobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job state returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
